### ISSUE TITLE
contract deploy successfully,but getCode return 0x ;no code at 

### ISSUE THREAD

**Issue by hecodev007** [FindoraNetwork/platform#101]
### Problem Description
>description:
no code at contract address.
>Screenshots:

### Environmental information
>operating system:

>service:

>Code version:

### Steps to reproduce
>1、
clone compound project from github,deploy Comptroller contract successfully 
>2、
can scan on https://blockscout.findorascan.io/address/0xEDECF0D00E1d737514F64f21fdB6aF530da1A428
>3、
but web3.eth.getCode("0x9f42De77AE4bD79658c6cB1A24774e08153A245F"); return 0x;
can sendtransaction ,but call function return error:CALL_EXCEPTION

**Comment by ws4charlie** [comment]
Could you also provide detailed steps(commands) as well. Thanks.

**Comment by hecodev007** [comment]
1:git clone https://github.com/compound-finance/compound-protocol.git
2:use hardhat deploy contract ,like follow
 const Comptroller = await ethers.getContractFactory("Comptroller");
    console.log("Deploying Comptroller...");
    let comptroller = await Comptroller.deploy();
    await comptroller.deployed();
   console.log("Comptroller Address is :", comptroller.address.toLocaleLowerCase());
    a = await  comptroller.getCompAddress();
     console.log(a.toString());

**Comment by kevinssgh** [comment]
What is this address referring to ? 
3、
but web3.eth.getCode("**0x9f42De77AE4bD79658c6cB1A24774e08153A245F**"); return 0x;
can sendtransaction ,but call function return error:CALL_EXCEPTION

**Comment by ws4charlie** [comment]
Kevin got this: https://blockscout.findorascan.io/address/0x0196115551E173658163E28F249147797e06Db56/transactions
when deploying the "Comptroller" contract using Redmix. It exceeds 24k limit. Need more input from ChingHua. Maybe Redmix was not proper tool to replicate the issue?

**Comment by frostfrog** [comment]
Using the command 
```
curl -H 'Content-Type: application/json' --data '{"method": "eth_getTransactionByHash", "jsonrpc":"2.0", "params":["0x5499c345c99959820423971ef2b8040d362c879c1b21c0dd8a7db718f803ca9f"], "id": 1}' https://prod-forge.prod.findora.org:8545 | jq .result
```
or 
```
web3.eth.getTransaction('0x5499c345c99959820423971ef2b8040d362c879c1b21c0dd8a7db718f803ca9f') 
```
we can get the input of the transaction and reproduce with this transaction with
```
web3.eth.sendTransaction()
```

**Comment by kevinssgh** [comment]
Thanks for helping us reproduce @frostfrog, The logs I found when deploying this data:

^[[2mNov 19 11:55:29.077^[[0m ^[[34mDEBUG^[[0m abciapp: app_hash_commit: 213a3d1c8675d3dfd3c2914b83de5647cb710af277c68d531d775298399125b3_82befb7bb82517c87318b5da685c4002a301c34ed76e8cbd9ca61907570b4bac, height: 30978
Invalid value length: 72489
^[[2mNov 19 11:55:29.529^[[0m ^[[31mERROR^[[0m evm: Failed inserting code (22641 bytes) at 0xb5a90d12515883c7a33aec179014d81b10ddb9fa, error: SimpleError { msg: SimpleMsg { err: "Invalid key-value pair detected.", file: "/Users/kevin/.cargo/git/checkouts/storage-aec2c479e7a64759/15c432a/src/state/mod.rs", line: 85, column: 17 }, cause: None }
Invalid value length: 72489
^[[2mNov 19 11:55:34.243^[[0m ^[[31mERROR^[[0m evm: Failed inserting code (22641 bytes) at 0xb5a90d12515883c7a33aec179014d81b10ddb9fa, error: SimpleError { msg: SimpleMsg { err: "Invalid key-value pair detected.", file: "/Users/kevin/.cargo/git/checkouts/storage-aec2c479e7a64759/15c432a/src/state/mod.rs", line: 85, column: 17 }, cause: None }
^[[2mNov 19 11:55:34.250^[[0m ^[[34mDEBUG^[[0m baseapp: deliver tx succeed result: ActionResult { code: 0, data: [123, 34, 67, 114, 101, 97, 116, 101, 34, 58, 123, 34, 101, 120, 105, 116, 95, 114, 101, 97, 115, 111, 110, 34, 58, 123, 34, 83, 117, 99, 99, 101, 101, 100, 34, 58, 34, 82, 101, 116, 117, 114, 110, 101, 100, 34, 125, 44, 34, 118, 97, 108, 117, 101, 34, 58, 34, 48, 120, 98, 53, 97, 57, 48, 100, 49, 50, 53, 49, 53, 56, 56, 51, 99, 55, 97, 51, 51, 97, 101, 99, 49, 55, 57, 48, 49, 52, 100, 56, 49, 98, 49, 48, 100, 100, 98, 57, 102, 97, 34, 44, 34, 117, 115, 101, 100, 95, 103, 97, 115, 34, 58, 34, 48, 120, 52, 98, 98, 100, 54, 57, 34, 44, 34, 108, 111, 103, 115, 34, 58, 91, 93, 125, 125], log: "", gas_wanted: 4963689, gas_used: 4963689, events: [type: "ethereum_TransactionExecuted" attributes {key: "sender" value: "0x13764f80adee76c4462d13a7ddd50c155b17299f"} attributes {key: "to" value: "0x0000000000000000000000000000000000000000"} attributes {key: "contract_address" value: "0xb5a90d12515883c7a33aec179014d81b10ddb9fa"} attributes {key: "transaction_hash" value: "0x8b8f278bc3df28e969258a7476b7a78a19e2f632ee330b3543450135b8d22b42"} attributes {key: "reason" value: "Succeed(Returned)"}] }

**Comment by kevinssgh** [comment]
https://github.com/FindoraNetwork/platform/pull/113

**Comment by kingpinXD** [comment]
Merged in this PR 
https://github.com/FindoraNetwork/platform/pull/115
