### ISSUE TITLE
Events in the contract event logs are  sorted backwards.

### ISSUE THREAD

**Issue by okovalov** [FindoraNetwork/platform#103]
### Problem Description
>description:

When the contract sends two transfers to two different addresses, the event logs are saved in the wrong order. Earlier event is located later than later event.

>Screenshots:

![CleanShot 2021-11-11 at 20 49 12@2x](https://user-images.githubusercontent.com/1706749/141394998-765c3b6c-3f8c-4f5f-85b0-3d239016b76a.png)

![CleanShot 2021-11-11 at 20 51 13@2x](https://user-images.githubusercontent.com/1706749/141395107-1e807082-0bfa-4252-bc6c-70b1c247646a.png)

that results in  a failing assertion, so instead of seeing a tx hash from the first block , in the first event, we have a tx hash from the later block.

<img width="667" alt="CleanShot 2021-11-11 at 20 52 59@2x" src="https://user-images.githubusercontent.com/1706749/141395242-ddc2dfc8-504d-407a-9716-bdcf552170d3.png">

### Environmental information
>operating system:

n/a running on "https://prod-forge.prod.findora.org:8545"

### Steps to reproduce
>1、

make sure your eth accounts (which are used to run the test) have enough balance and run `yarn test:evm:integration:contract:devnet `

**Comment by okovalov** [comment]
@jianwel and same issue persists when a contract is sending funds to receivers and the send process triggered externally, by another contract 
<img width="993" alt="CleanShot 2021-11-11 at 21 16 21@2x" src="https://user-images.githubusercontent.com/1706749/141397477-c67b6fac-ef40-4684-9c6f-4532eb904c50.png">

<img width="1008" alt="CleanShot 2021-11-11 at 21 18 01@2x" src="https://user-images.githubusercontent.com/1706749/141397553-0980d848-850c-47c2-bed6-f44cb755f3f9.png">

**Comment by ws4charlie** [comment]
![image](https://user-images.githubusercontent.com/34498985/142748102-7b8437c9-a51d-478e-bc66-038bc0f077de.png)
`yarn test:evm:integration:contract:devnet` passed after fix: https://github.com/FindoraNetwork/platform/pull/114/files

**Comment by okovalov** [comment]
@ws4charlie nice fix , thank you! good job! closing this one.
