### ISSUE TITLE
`self_delegation`  amount is 0 by chance in validator_delegation

### ISSUE THREAD

**Issue by zTgx** [FindoraNetwork/platform#109]
### Problem Description
>description:

https://prod-mainnet.prod.findora.org:8668/validator_delegation?address=09EF1DB6B67D1CBF7EBA6BD9B204611848993DF7&epoch_size=5400&epoch_cnt=20

>Screenshots:
![91544c9b51cdc716f34c9dfd88384e2](https://user-images.githubusercontent.com/49638837/141887313-36b4731c-64b8-4099-9aef-37923f4d5963.png)

### Environmental information
>operating system:

>service:

>Code version:

### Steps to reproduce
>1、

>2、

>3、

**Comment by kingpinXD** [comment]
Related to Issue 147
