### ISSUE TITLE
evm>native transfer error

### ISSUE THREAD

**Issue by DomFeng** [FindoraNetwork/platform#129]
### Problem Description
>description:
evm>native transfer error

>Screenshots:
![image](https://user-images.githubusercontent.com/61138066/143198098-354a6d81-c8c9-4830-8163-7375a7539316.png)

### Environmental information
>operating system:
macos

>service:
https://dev-qa02.dev.findora.org

>Code version:
Build: testnet-evm-v0.2.6b 2021-11-22

### Steps to reproduce
>1、evm>native transfer

**Comment by ws4charlie** [comment]
Strange. I have been using a wallet installer from here: https://wiki.findora.org/docs/dapp/wallet
And internal transfer works well for me on QA02.
![image](https://user-images.githubusercontent.com/34498985/143323361-e15b781b-768b-465e-99a3-c23b62f0071c.png)

**Comment by ws4charlie** [comment]
@tiannian same error as #130 , right?

**Comment by tiannian** [comment]
I think it's the same reason as #130. We can using devtool in electron to comfirm it. Click the version ten times to see the devtool. @DomFeng

**Comment by ws4charlie** [comment]
The issue was resolved after Jimmy enabled requests of broadcast_tx_sync, broadcast_tx_async etc. I verified.
@DomFeng Would you like to verify again?

**Comment by ws4charlie** [comment]
The issue was resolved after Jimmy enabled requests of broadcast_tx_sync, broadcast_tx_async etc.
![image](https://user-images.githubusercontent.com/34498985/143981911-cf21ab70-cff5-4da0-b7a1-0f823119a9f0.png)
