### ISSUE TITLE
fn failed to get balance of eth account

### ISSUE THREAD

**Issue by simonjiao** [FindoraNetwork/platform#130]
### Problem Description
>description:
`fn` command panicked when querying eth account balance 
>Screenshots:
![图片](https://user-images.githubusercontent.com/6870378/143344693-8f8d919a-7c02-440c-9a44-e605d6b385e5.png)

### Environmental information
>operating system:
![图片](https://user-images.githubusercontent.com/6870378/143345443-639503b1-308b-4f4b-8b8e-e4d446340174.png)

>service:
https://dev-qa02.dev.findora.org
>Code version:
Build: testnet-evm-v0.2.6b 2021-11-22

### Steps to reproduce
>1、

>2、

>3、

**Comment by simonjiao** [comment]
start a local fullnode of qa02, `fn` works just fine
![图片](https://user-images.githubusercontent.com/6870378/143417222-be4a23f1-7a7f-4d81-812f-01cf6f3584e1.png)
This issue should be caused by online environment of qa02 fullnodes.

**Comment by simonjiao** [comment]
![图片](https://user-images.githubusercontent.com/6870378/143561211-5fb1acc8-64e5-4970-9ccf-fbdcc89914a6.png)

**Comment by ws4charlie** [comment]
The issue was resolved after Jimmy enabled requests of broadcast_tx_sync, broadcast_tx_async etc.
