### ISSUE TITLE
evm block chain browser to view evm transaction details, click hash and report 502

### ISSUE THREAD

**Issue by DomFeng** [FindoraNetwork/platform#134]
### Problem Description
>description:
evm block chain browser to view evm transaction details, click hash and report 502

>Screenshots:
![image](https://user-images.githubusercontent.com/61138066/143826797-3ebb2055-4f52-435e-ad6e-4aaf883c61b0.png)
![image](https://user-images.githubusercontent.com/61138066/143827083-0d210786-0a9e-4e0a-9cbd-ca68fa6711b2.png)

### Environmental information
>operating system:
ubuntu

>service:
findora

>Code version:
qa02:Build: testnet-evm-v0.2.7a 2021-11-26

### Steps to reproduce
>1、open http://mainnetmock-findorascan-io.s3-website-us-west-2.amazonaws.com/transactions

>2、View evm transaction details

**Comment by kingpinXD** [comment]
@HelloRickey  What is the expected behaviour here ? should it be opening the corresponding blockscout link?

**Comment by HelloRickey** [comment]
> @HelloRickey What is the expected behaviour here ? should it be opening the corresponding blockscout link?

This should not be a bug, because we currently do not deploy blockscout in the mainnet-mock environment.
