### ISSUE TITLE
get block by hash sometimes returns NULL

### ISSUE THREAD

**Issue by okovalov** [FindoraNetwork/platform#135]
### Problem Description
when trying to get data by block hash (i.e. using `eth_getTransactionByBlockHashAndIndex` or `eth_getBlockByHash`) returned response is null, even though the transaction has been broadcasted successfully and receipt has been received (so the block is valid as well as its hash).

The problem happens NOT all the time. Sometimes both methods calls return the result (transaction or block), like in the attached video - this time we could get block data but could not get transaction data. Sometimes both methods fail. Sometimes both are passing, which makes it tricky to test and catch the reason.

>Screenshots:

https://user-images.githubusercontent.com/1706749/143919892-921c72b1-c460-4f70-99f9-b9438753e7c2.mp4

### Environmental information
>env:
Forge

### Steps to reproduce
>1、configure your `.env_rpc_dev.json` and provide proper host url and mnemonic of the account which has EVM FRAfor first 4 addresses

>2、run `yarn test:emv:integration:rpc:devnet`

**Comment by ws4charlie** [comment]
Were those blocks/txns permanant lost or they could be successfully fetched after many blocks? @okovalov

**Comment by ws4charlie** [comment]
Can you also check QA02?

**Comment by kingpinXD** [comment]
Asigning to @okovalov  to check

**Comment by okovalov** [comment]
> Were those blocks/txns permanant lost or they could be successfully fetched after many blocks? @okovalov

I think If you check that later, (like you said, after many blocks) you do have it. as I have said,  sometimes the block is found , so the test is passing. the problem is that SOMETIMES , even though we have a tx receipt , the block is not found

**Comment by okovalov** [comment]
> Can you also check QA02?

yes, there is an issue with the wrong / not found block on qa02 as well 
![CleanShot 2021-11-30 at 13 10 20@2x](https://user-images.githubusercontent.com/1706749/144103948-d22f463c-e9b0-46e2-a6e3-dd304115667e.png)

**Comment by okovalov** [comment]
@kingpinXD  @ws4charlie it seems to be that the issue does not happen on qa02 as for now.  I am assuming that it is only forge related problem.

```
 PASS  src/evm/rpc.integration.spec.ts (41.636 s)
  Api Endpoint (rpc test) for "https://dev-qa02.dev.findora.org:8545"
    eth_protocolVersion
      ✓ Returns the current ethereum protocol version (382 ms)
    eth_chainId
      ✓ Returns the current chain id (288 ms)
    eth_accounts
      ✓ Returns a list of addresses owned by client (282 ms)
    eth_getBalance
      ✓ Returns the balance of the account of given address (286 ms)
    eth_sendTransaction
      ✓ Creates new message call transaction or a contract creation, if the data field contains code (275 ms)
    eth_call
      ✓ Executes a message immediately without creating a transaction (280 ms)
    eth_coinbase
      ✓ Returns the client coinbase address (273 ms)
    eth_gasPrice
      ✓ Returns the current price per gas in wei (293 ms)
    eth_blockNumber
      ✓ Returns the number of most recent block (278 ms)
    eth_getBlockByHash
      ✓ Returns information about a block by hash (287 ms)
    eth_getBlockByNumber
      ✓ Returns information about a block by block number. (279 ms)
    eth_getTransactionCount
      ✓ Returns the number of transactions SENT from an address (273 ms)
    eth_getBlockTransactionCountByHash
      ✓ Returns the number of transactions in a block from a block matching the given block hash (280 ms)
    eth_getBlockTransactionCountByNumber
      ✓ Returns the number of transactions in a block from a block matching the given block number (274 ms)
    eth_getCode
      ✓ Returns code at a given address (275 ms)
    eth_sendRawTransaction
      ✓ Creates new message call transaction or a contract creation for signed transactions (negative case) (271 ms)
    eth_estimateGas
      ✓ Generates and returns an estimate of how much gas is necessary to allow the transaction to complete (269 ms)
    eth_getTransactionByHash
      ✓ Returns the information about a transaction requested by transaction hash (278 ms)
    eth_getTransactionByBlockHashAndIndex
      ✓ Returns information about a transaction by block hash and transaction index position (270 ms)
    eth_getTransactionByBlockNumberAndIndex
      ✓ Returns information about a transaction by block number and transaction index position (270 ms)
    eth_getTransactionReceipt
      ✓ Returns the receipt of a transaction by transaction hash (286 ms)
    eth_getLogs
      ✓ Returns an array of all logs matching a given filter object (290 ms)

```

**Comment by okovalov** [comment]
@ws4charlie @kingpinXD if that is an env problem, (I guess we can assume that) I think it is ok to resolve it? assigning to you guys, so you can decide.

**Comment by kingpinXD** [comment]
I am okay to resolve this
