### ISSUE TITLE
0x1000 precompile contract is not fully compatible with IERC20 in solidity.

### ISSUE THREAD

**Issue by frostfrog** [FindoraNetwork/platform#146]
### Problem Description
>description:
Solidity will add an `extcodesize` check if the code is still there. 
So if I use [IERC20](https://github.com/Uniswap/v2-core/blob/master/contracts/interfaces/IERC20.sol) here to interact with our precompile contracts. It would failed.

>Screenshots:

### Steps to reproduce
>1、
Use the IERC20 token to implement a smart contract
>2、
Use the contract to interact with 0x1000
>3、
Transaction will revert by `iszero` after `extcodesize`

**Comment by ws4charlie** [comment]
@frostfrog  Is this a related topic: https://github.com/ethereum/solidity/issues/12204.

**Comment by hrkrshnn** [comment]
@ws4charlie What exactly was the problem here? We were wondering about how the change related to precompile would affect users. As this was undocumented, and since precompiles don't follow the ABI conventions, we proceeded to ship that optimization.
