### ISSUE TITLE
Unhandled error from zen library while trying to open client asset record

### ISSUE THREAD

**Issue by okovalov** [FindoraNetwork/platform#170]
### Problem Description
>description:

After fetching Sid from `https://dev-qa01.dev.findora.org:8668/utxo_sid/14659` we are decrypting utxo item and during that process we:

1. recover client record from the response of the network call above (using  `ledger.ClientAssetRecord.from_json`)

<img width="788" alt="CleanShot 2021-12-14 at 17 10 06@2x" src="https://user-images.githubusercontent.com/1706749/146087366-696e422f-64e8-4fb7-a0f7-fd8100090a04.png">

2. then we are retrieving owner memo (using `ledger.OwnerMemo.from_json` ) and trying to open client asset record (using `ledger.open_client_asset_record`)

<img width="925" alt="CleanShot 2021-12-14 at 17 12 19@2x" src="https://user-images.githubusercontent.com/1706749/146087592-405b1449-4044-41ba-9a75-efb0f99c2a1d.png">

and that is where the issue happens. and no meaningful error details are provided except that it is an unhandled error thrown by zei api. 

<img width="973" alt="CleanShot 2021-12-14 at 17 12 46@2x" src="https://user-images.githubusercontent.com/1706749/146087772-5fed4b67-333d-426e-a3a0-3364fdae5f85.png">

This issue happens for some sids (utxo) and `14659` is one of those. for other sids decryption works fine.

>Screenshots:

are provided above, in the description

### Environmental information
> it was found on `https://dev-qa01.dev.findora.org`

### Steps to reproduce
> 1. run `yarn start` in the sdk using private key or mnemonic of the main _faucet_ (I can provide that info in a private channel)
or, alternatively we could run it from this code snippet (_this is just an example_)

```ts

import findoraSdk from "@findora-network/findora-sdk.js";

const sdkEnv = {
  hostUrl: "https://dev-qa01.dev.findora.org",
  cachePath: "./cache",
};

const { default: SdkInstance } = findoraSdk.Sdk;

const {
  Keypair: KeypairApi,
  Account: AccountApi,
} = findoraSdk.Api;

SdkInstance.init(sdkEnv);

const main = async () => {
  const pkey = 'TO_BE_PROVIDED';
  const password = '123';

  const walletInfo = await KeypairApi.restoreFromPrivateKey(pkey, password);

  const balance = await AccountApi.getBalance(walletInfo);
};

main();
```

**Comment by ws4charlie** [comment]
The query `https://dev-qa01.dev.findora.org:8668/get_owner_memo/14659` returned null. That was why wallet couldn't correctly open that UTXO. `fn` queries owner memo from a different API so it successfully fetched its owner memo and then opened that UTXO. @tiannian is doing investigation into this `get_owner_memo` API.

**Comment by tiannian** [comment]
Fixed on code, wait checking and deploy
