### ISSUE TITLE
Data display problem in ‘other’ transaction records

### ISSUE THREAD

**Issue by DomFeng** [FindoraNetwork/platform#175]
### Problem Description
>description:
目前‘其他’交易记录中
1、不显示cliam记录
2、不显示evm>native交易记录
3、不显示unstake交易记录

>Screenshots:
![image](https://user-images.githubusercontent.com/61138066/146350154-63ba64d2-de44-4d99-91cc-c5bb2e7ab35c.png)

### Environmental information
>operating system:
ubuntu

>service:
https://prod-mainnet.prod.findora.org/

>Code version:
Build: v0.3.5-release 2021-12-14

### Steps to reproduce
>1、claim

>2、evm>native transfer

>3、unstake

**Comment by tiannian** [comment]
Same as #172
