### ISSUE TITLE
Unit test working inconsistently

### ISSUE THREAD

**Issue by hridambasu** [FindoraNetwork/platform#212]
### Problem Description
>description:
The unit test txn_builder::tests::axfr_create_verify_unit_positive_tests_with_fees (https://github.com/FindoraNetwork/platform/blob/feat-triple-masking-v3/src/components/finutils/src/txn_builder/mod.rs#L1710) is working when running in the single thread but when 'cargo test' is used and the test is running on multiple threads, it fails. 
>Screenshots:

### Environmental information
>operating system:
MAC OS Monterey 12.0.1
>service:

>Code version:
Branch: feat-triple-masking-v3

### Steps to reproduce
>1、Run 'cargo test', the test fails.

>2、Run 'cargo test txn_builder::tests::axfr_create_verify_unit_positive_tests_with_fees', the test passes.

**Comment by harshadptl** [comment]
This is happening because in multithread environment there are some tests using common files on the filesystem and experiencing race conditions. Running the unit tests in single threaded environment is recommended.
