### ISSUE TITLE
RPC test on local evm (send a tx to an eth address from another eth address) crashes the node0

### ISSUE THREAD

**Issue by okovalov** [FindoraNetwork/platform#25]
### Problem Description
As a pre-requisite of running a simple rpc test, I am trying to send a transaction (to be able to get a tx hash and block hash, as wee as the tx receipt).

```js
beforeAll(async (done: any) => {
  const transactionObject = {
    from: ethAccountToCheck,
    to: ethContractAddressToReceive,
    value: '1000000000000000',
    gas: 1000000,
    gasPrice: 700000000000,
  };

  web3.eth
    .sendTransaction(transactionObject)
    .once('sending', function (_payload) {
      console.log('🚀 ~ IT IS SENDING file: rpc.spec.ts ~ line 37 ~ payload', _payload);
    })
    .once('sent', function (_payload) {
      console.log('🚀 ~ IT IS SENT file: rpc.spec.ts ~ line 40 ~ payload', _payload);
    })
    .once('transactionHash', function (_hash) {
      console.log('🚀 ~ file: rpc.spec.ts ~ line 44 ~ hash', _hash);
    })
    .once('receipt', function (_receipt) {
      console.log('🚀 ~ file: rpc.spec.ts ~ line 45 ~ receipt', _receipt);
    })
    .on('error', function (_error) {
      console.log('🚀 ~ ERROR file: rpc.spec.ts ~ line 51 ~ error', _error);
      done();
    })
    .then(function (receipt) {
      console.log('🚀 ~ file: rpc.spec.ts ~ line 60 ~ receipt', receipt);
      // will be fired once the receipt is mined
      const { transactionHash, blockHash, blockNumber } = receipt;

      // This block number has to be from the block `existingBlockHashToCheck`
      existingBlockNumberToCheck = blockNumber;
      // This block hash must be from the block `existingBlockNumberToCheck`
      existingBlockHashToCheck = blockHash;
      // This tx hash must be from the block `existingBlockNumberToCheck`
      existingTxHashToCheck = transactionHash;
      done();
    });
}, extendedExecutionTimeout);
```

every other time causes a crash of node0 

**How to reproduce:**

https://user-images.githubusercontent.com/1706749/135687486-52eea82f-08c2-400d-821a-c2754aeee163.mp4

### Environmental information
>operating system:
mac os

>Code version:
`develop` branch on this hash
<img width="1087" alt="CleanShot 2021-10-01 at 17 22 01@2x" src="https://user-images.githubusercontent.com/1706749/135687578-a3cc3c59-e8d4-4356-b0ba-e1980d35a357.png">

### Steps to reproduce
>1、
Spin up a local env, send some balance to the eth address
>2、
Check the network responses from version and status, to make sure rpc and nodes are responding
>3、
Run rpc test from `sdk` repo and see its throwing an error
>4、
again check the network responses from version and status, to make sure rpc and nodes are not responding and also by checking ps list, see that only node1 is running

**Comment by ws4charlie** [comment]
fixed in develop branch
