### ISSUE TITLE
Local env faucet account is created with 0 FRA balance

### ISSUE THREAD

**Issue by okovalov** [FindoraNetwork/platform#26]
### Problem Description
After running `make devnet` to create a local env, the faucet account is ver often created with no balance. 

>Screenshots:

https://user-images.githubusercontent.com/1706749/135690912-4f4d3052-b6e6-478d-9dfc-5623dab3709c.mp4

### Environmental information
>operating system:
mac os

>Code version:
`develop` branch on this hash

<img width="982" alt="CleanShot 2021-10-01 at 18 07 30@2x" src="https://user-images.githubusercontent.com/1706749/135691238-11131e95-4249-4608-ad12-a2fb0bb1b685.png">

### Steps to reproduce
>1、
run `make devnet` and check all the services are running and returning a response (like rpc, status, version ) also check for ps list for abcid 
>2、
check the balance - you see 0
>3、
run `./tools/devnet/stopnodes.sh` to stop the env and then `make devnet` again. (like repeat step 1) - problem persists.
>4、
stop devnet again and remove `~/test/devnet` and run `cargo update` and `cargo build` and repeat step ` - now it solved (sometimes it requires to repeat step 4 again)..

**Comment by okovalov** [comment]
@kingpinXD @ws4charlie that seems like just a matter of time when node crashes . it runs for like 10 minutes and then BOOM

<img width="1323" alt="CleanShot 2021-10-01 at 18 48 03@2x" src="https://user-images.githubusercontent.com/1706749/135693701-1dc6dbfc-3176-4ea3-969c-acb719730006.png">

**Comment by ws4charlie** [comment]
fix merged into develop already
