### ISSUE TITLE
Triple Masking: Abar to Bar `add_operation_anon_fee` throws an error

### ISSUE THREAD

**Issue by okovalov** [FindoraNetwork/platform#264]
### Problem Description

When trying to perform abar to bar conversion, at the step of adding anon fee , there is a error being thrown (null pointer being passed to rust)

>Screenshots:

![CleanShot 2022-03-31 at 13 23 16](https://user-images.githubusercontent.com/1706749/161113940-eb5d7d71-1ab0-4908-b4d3-2d86714381d7.png)

### Environmental information
>operating system:
Mac OS

>Code version:
`feat_fo_931_abar_to_bar` for sdk and `feat-triple-masking-v3` for platform

### Steps to reproduce
>1、
Configure your local env to use triple masking branch and have your account funded from the faucet and some abars being sent to a new anon wallet

>2、
please used SDK branch `feat_fo_931_abar_to_bar` ,  please note, that `abarToBar` function in `run.ts` needs to have your own abar and randomizers info, as well as the wallet info where the abar needs to be sent to and the sender anon wallet info

ie. 

```ts
  const walletInfo = await Keypair.restoreFromPrivateKey(pkey, password);

  const anonKeysSender = {
    axfrPublicKey: 'oDosEZB9uq4joxcM6xE993XHdSwBs90z2DEzg7QzSus=',
    axfrSecretKey: 'Gsppgb5TA__Lsry9TMe9hBZdn_VOU4FS1oCaHrdLHQCgOiwRkH26riOjFwzrET33dcd1LAGz3TPYMTODtDNK6w==',
    decKey: 'oAOZEUWKbgjv8OVtlL5PJYrNnV1KDtW3PCyZc30SW0Y=',
    encKey: 'eT39SV2et8ONJsN0kCEPJkNQys89UlFUsdPpY2x5qR8=',
  };

  // rnadomizer for abar to be sent
  const givenRandomizerOne = '3PaExNx4SXNnhhE2pVpNiNHpiSXFQThh8qPgUycUDG5G';

  // randomizer to pay fee
  const givenRandomizerTwo = '3NcCcc493iSc2QcTuEGVwSb5vLDHDVpHHEcPPCPUN9Bp';

  const ownedAbarsResponseOne = await TripleMasking.getOwnedAbars(
    anonKeysSender.axfrPublicKey,
    givenRandomizerOne,
  );
```

>3、
run `yarn` and `yarn start`.

**Comment by harshadptl** [comment]
This is fixed in commit https://github.com/FindoraNetwork/platform/pull/237/commits/bfc9a61c8975497529a1aae12c3c86c7e3e65da8
