### ISSUE TITLE
EVM update smart contract data does not work and breaks evm

### ISSUE THREAD

**Issue by okovalov** [FindoraNetwork/platform#27]
### Problem Description
>description:
When trying to update a data on a deployed smart contract, it crashes the node0

>Screenshots:

https://user-images.githubusercontent.com/1706749/135695974-fc7db1d9-52dc-4ab2-999e-4dc30e526b37.mp4

### Environmental information
>operating system:
mac os
>service:

>Code version:

`develop` on this hash 
<img width="1078" alt="CleanShot 2021-10-01 at 19 35 36@2x" src="https://user-images.githubusercontent.com/1706749/135696011-ceb6ce29-99f4-4345-8d83-a2fa750cfb7a.png">

### Steps to reproduce
>1、
having local findora evm running, execute smart contract test by running `yarn test:contract:create` from SDK. that would create and deploy a smart contract and run tests , and last ne is the one which is failing 

<img width="989" alt="CleanShot 2021-10-01 at 19 38 17@2x" src="https://user-images.githubusercontent.com/1706749/135696147-ad236ee3-d9d9-4c74-944a-a6be85bf2cd8.png">

**Comment by tylerztl** [comment]
Can you provide the contract code? Or under the devnet test, my local test is normal.

**Comment by okovalov** [comment]
@tylerztl hi Tyler. sure. here it is the [contract code](https://github.com/FindoraNetwork/findora-sdk/blob/fo_459_evm_tests/src/evm/contracts/Inbox/Inbox.sol), and here is the [test](https://github.com/FindoraNetwork/findora-sdk/blob/fo_459_evm_tests/src/evm/contracts/Inbox/Inbox.contract.spec.js)

**Comment by okovalov** [comment]
that is fixed 
```
 PASS  src/evm/contracts/Inbox/Inbox.contract.spec.js (48.461 s)
  Inbox (contract test)
    ✓ deploys a contract successfully (4345 ms)
    ✓ deploys a contract with a default assigned message (6556 ms)
    ✓ updates a message with a given value (15482 ms)


```
