### ISSUE TITLE
Triple Masking: Remainder returned after air to bar is not found (does not belong to the sender anon wallet)

### ISSUE THREAD

**Issue by okovalov** [FindoraNetwork/platform#270]
### Problem Description
>description:

so, after running Abar to bar, I receive a new randomizer. (with a remainder of the fee).
Then, after querying owned bars by this randomizer, we have a response with a atxo sid (in this example it is 3), I am querying abar memo with a given atxo sid 3 and getting null as a response.

However, for another randomizer I have both owned owned bars (by the randomizer) and using a sid (in this example 2) I can get abar memo.

>Screenshots:

<img width="1171" alt="CleanShot 2022-04-01 at 16 20 42@2x" src="https://user-images.githubusercontent.com/1706749/161336010-7686ab67-2696-4029-822e-1bdb70664ba5.png">

### Environmental information
>operating system:
Mac os

>Code version:
platform `feat-triple-masking-v3` sdk `feat_fo_931_abar_to_bar` 

### Steps to reproduce
>1、
perform abar to bar transfer in sdk , save the returned randomizer and try to check its balance.
then, for comparison check the balance of another randomizer (which was not created from a remainder but was created as a result of bar to abr transfer)

**Comment by harshadptl** [comment]
This is fixed in PR https://github.com/FindoraNetwork/platform/pull/269
