### ISSUE TITLE
When sending a few tx to the address right next to each other, and checking the balance,  a node is taken down

### ISSUE THREAD

**Issue by okovalov** [FindoraNetwork/platform#275]
### Problem Description
>description:
SO if you are sending a few tx to the same address and checking the balance of the sender and the receiver right after the send, we might pretty easy have a situation that a node brakes down and stop responding. 

I have talked to @harshadptl and as per him , this issue whorls be fixed in this PR https://github.com/FindoraNetwork/platform/pull/273#issuecomment-1090498808 but that needs to be checked.

>Screenshots:

![CleanShot 2022-04-06 at 14 00 17](https://user-images.githubusercontent.com/1706749/162038999-42f87b46-48f6-4500-8fcf-400dba92d2a3.png)

### Environmental information
>operating system:
MackOS

>service:
Findora SDK

>Code version:
platform `develop` branch on this hash
![CleanShot 2022-04-06 at 14 04 40](https://user-images.githubusercontent.com/1706749/162039561-146c7c13-9eec-4d89-93ba-b8d27e88dbb5.png)

ask is on this hash 
![CleanShot 2022-04-06 at 14 05 08](https://user-images.githubusercontent.com/1706749/162039702-a5f096b8-1749-4ae7-99bd-548c14864392.png)

### Steps to reproduce
>1、set up local platform

>2、
in one terminal run `yarn start` (configure run.ts to check frames balance)

>3、
in another terminal run several transfers using sdk cli

**Comment by harshadptl** [comment]
https://github.com/FindoraNetwork/platform/pull/273
