### ISSUE TITLE
When have enough fee for abar transfer, still unable to build and sign the operation

### ISSUE THREAD

**Issue by okovalov** [FindoraNetwork/platform#279]
### Problem Description
>description:

When trying an abar transfer, at the step of `build_and_sign` I am getting an error, which is apparently caused by non-sufficient fee. But, `get_expected_fee` method returns 0, meaning no fee needs to be added. 
>Screenshots:

![CleanShot 2022-04-07 at 18 48 17](https://user-images.githubusercontent.com/1706749/162332053-b1e7d287-2c71-4c87-ac92-f79986dfce56.png)

However, when I am trying to use a very small abar, I do see a handled error, when expected fee amount is > 0

![CleanShot 2022-04-07 at 18 56 54](https://user-images.githubusercontent.com/1706749/162332824-ffddd249-d979-4bea-becf-ec30352b20c8.png)

![CleanShot 2022-04-07 at 18 57 45](https://user-images.githubusercontent.com/1706749/162332831-47a64a28-a4ff-455f-9dee-4140ff76cb40.png)

### Environmental information
>operating system:
MacOS

>service:

SDK Triple Masking API

>Code version:
SDK - `feat_fo_784_abar_to_abar`
on this hash 
```
commit a17d91198ea885afba7a4ac9744779353d0e2a01 (HEAD -> feat_fo_784_abar_to_abar)
Author: Oleksandr Kovalov <oleksandr.kovalov@gmail.com>
Date:   Thu Apr 7 18:52:55 2022 -0400

    feat: fo-784: add fee estimator method to triple masking sdk, refactor abar transfer

```

platform - `develop`

on this hash 
```
commit c97e3b8418887e38cf7db640e25dadaebe081606 (HEAD -> develop, origin/develop)
Author: shaitao <35680000+shaitao@users.noreply.github.com>
Date:   Wed Apr 6 13:45:38 2022 +0800

    Get more error infomation in config. (#274)


```
### Steps to reproduce
>1、prepare 3 abars

![CleanShot 2022-04-07 at 18 54 45](https://user-images.githubusercontent.com/1706749/162332595-dc7be1e2-95d0-429d-aad4-dbc7a2f1d13d.png)

that would return 0 as an expected fee

![CleanShot 2022-04-07 at 18 55 24](https://user-images.githubusercontent.com/1706749/162332645-d0fe99e4-f52e-46e3-8268-5996a08722d7.png)

>2、run abar transfer 

![CleanShot 2022-04-07 at 18 56 01](https://user-images.githubusercontent.com/1706749/162332685-8c9883d2-6f81-45e6-84d7-8fa5c4f3623b.png)

**Comment by harshadptl** [comment]
https://github.com/FindoraNetwork/platform/pull/281
