### ISSUE TITLE
Abar from customer asset is not being transferred and throwing an error even though the amount matches required 

### ISSUE THREAD

**Issue by okovalov** [FindoraNetwork/platform#282]
### Problem Description
>description:

Trying to transfer an abar created from a custom asset, I am getting an error (even though the transferred amount equals to the abar amount)

![CleanShot 2022-04-08 at 21 41 10](https://user-images.githubusercontent.com/1706749/162551645-ce772fa0-1a01-45c7-a5c2-9651a7105679.png)

>Screenshots:

sids which are used have amounts of 20 FRA (to pay fee, atxo 5) and 3 TEST3 (custom asset abar to be transferred, atxo 1)

![CleanShot 2022-04-08 at 21 32 57](https://user-images.githubusercontent.com/1706749/162551344-31a6d2cd-8c33-4fc2-891d-3a1a58db94f2.png)

![CleanShot 2022-04-08 at 21 33 09](https://user-images.githubusercontent.com/1706749/162551356-d169431e-5638-4c1e-b67e-85f0782e45ac.png)
 
corresponding randomizers are (amount to be transferred is matching with the amount of the abar): 

![CleanShot 2022-04-08 at 21 34 09](https://user-images.githubusercontent.com/1706749/162551453-dfbabce8-ee12-465c-afc4-12acb7d53e2c.png)

### Environmental information
>operating system:
mac os

>service:
Findora SDK

>Code version:
SDK no this hash `5584cb166f486cdc85913d0c07c8d943669fa349` 

branch `feat_fo_784_abar_to_abar`

![CleanShot 2022-04-08 at 21 43 37](https://user-images.githubusercontent.com/1706749/162551721-0ae39e8a-f7be-4e84-945a-9ce4c8ec8b1d.png)

platform on `develop` branch, hash  `bdabc60cceb4d382a7c2ab55afd3b2296987e347`

![CleanShot 2022-04-08 at 21 44 24](https://user-images.githubusercontent.com/1706749/162551744-10240610-63a0-47b7-aadb-a37306868122.png)

### Steps to reproduce
>1、checkout SDK, run `yarn` 

>2、prepare local abars to match the test case and update `tun.ts` accordingly

>3、run `yarn start`

**Comment by okovalov** [comment]
looks like the problem is back. custom asset abar is not being transferred
![CleanShot 2022-05-05 at 18 12 35](https://user-images.githubusercontent.com/1706749/167034134-b2c2299d-76d5-441c-a6e5-3dae1e8ae8b6.png)

**Comment by harshadptl** [comment]
This is fixed in https://github.com/FindoraNetwork/platform/pull/302
