### ISSUE TITLE
Commitment hash in the tx history for BarToAbr is in base64 however it should be in base58

### ISSUE THREAD

**Issue by okovalov** [FindoraNetwork/platform#327]
### Problem Description
>description:

Commitment hash in the tx history for BarToAbr is in base64 however it should be in base58
So it is not possible to map the commitment retrieved as a result from the transaction builder operation with those which come from the tx history

>Screenshots:

![CleanShot 2022-06-03 at 18 43 51](https://user-images.githubusercontent.com/1706749/171964592-06241572-6f23-429e-acd7-d2e0d6d2fbc7.png)

![CleanShot 2022-06-03 at 18 41 30](https://user-images.githubusercontent.com/1706749/171964597-23675ea3-812c-448e-a7df-13ce5a8adfa6.png)

### Environmental information
>operating system:

>service:
TripleMasking

>Code version:

develop branch 

![CleanShot 2022-06-03 at 18 40 00](https://user-images.githubusercontent.com/1706749/171964628-0d14ba35-a72b-4b24-af2a-86ddd7d1f8db.png)

**Comment by harshadptl** [comment]
Have added a utility function in wasm to convert base64 to base58 for SDK. Closing this issue
