### ISSUE TITLE
contract deposit to EVM account burns far on far account and not adding to evm account

### ISSUE THREAD

**Issue by okovalov** [FindoraNetwork/platform#372]
### Problem Description
>description:
When doing contract deposit from an fra account to a evm account `0x` , funds are taken from the fra account but they are added to the `0x` account even after a long waiting time

>Screenshots:

https://user-images.githubusercontent.com/1706749/177817111-ab4e589c-aadb-4a89-9f1f-15673aff2b1a.mp4

### Environmental information
>operating system:
mac os

>service:
evm

>Code version:
platform `develop` branch on this commit
```
commit df1f28c90c4e7687ceb89639cc7f228f9026fe14 (HEAD -> develop, origin/develop)
Author: Harshad Patil <harshad0402@gmail.com>
Date:   Wed Jul 6 13:53:04 2022 -0700

    Example checkpoint file for running devnet with all features (#367)

commit 8e112ae14d4b35bee2594ac16856e30beca58c85
Author: tiannian <dtiannian@gmail.com>
Date:   Wed Jul 6 18:44:14 2022 +0800

    fix error of pending txs

commit 23c15ad6be56cc421a4ee7a8bbb4e8d9672a5906
Author: tiannian <dtiannian@gmail.com>
Date:   Wed Jul 6 10:59:47 2022 +0800

    step to process confilct

```

### Steps to reproduce
>1、
check the balance of the faucet, and see and memorize its value

target/release/fn show -b

>2、
send the funds to the `0x` account
target/release/fn contract-deposit --addr 0x9257e1aeb58e16a9c33e0e8469a1d5205d6350b8  --amount 10000000

>3、
wait for a minute and check the balance for the faucet account again and see its changed 

target/release/fn show -b

>4、
check the balance for the `0x` account and see it is not changed

target/release/fn account -a 0x9257e1aeb58e16a9c33e0e8469a1d5205d6350b8

**Comment by tiannian** [comment]
develop branch?

**Comment by okovalov** [comment]
@tiannian yeah. develop (I have mentioned that in the description, you probably did not notice) 
![CleanShot 2022-07-07 at 13 43 37](https://user-images.githubusercontent.com/1706749/177836655-c92bcfe7-7039-4cf9-8635-b76806b497d5.png)

**Comment by okovalov** [comment]
@dlin128 @ws4charlie @harshadptl @tiannian @jianwel , guys it is passing now, so I am closing this issue. please see local test results at FO-1037
