### ISSUE TITLE
updating checkpoint.toml with a 0 value causes the node0 crash after the utxo transaction

### ISSUE THREAD

**Issue by okovalov** [FindoraNetwork/platform#373]
### Problem Description
>description:
If i update `checkpoint.toml` with 0 set as the value or the parameter, and then I run an utxo tx , that causes the node0 crash. that does not happen with values generated by default (by running `make devnet`)

A very detailed explanation and step by step reproducible process is in the video

>Screenshots:

https://youtu.be/Vnw_iryax0g

### Environmental information
>operating system:

>service:

>Code version:

platform of `develop` branch,

```
commit df1f28c90c4e7687ceb89639cc7f228f9026fe14 (HEAD -> develop)
Author: Harshad Patil <harshad0402@gmail.com>
Date:   Wed Jul 6 13:53:04 2022 -0700

    Example checkpoint file for running devnet with all features (#367)

commit 8e112ae14d4b35bee2594ac16856e30beca58c85
Author: tiannian <dtiannian@gmail.com>
Date:   Wed Jul 6 18:44:14 2022 +0800

    fix error of pending txs

commit 23c15ad6be56cc421a4ee7a8bbb4e8d9672a5906
Author: tiannian <dtiannian@gmail.com>
Date:   Wed Jul 6 10:59:47 2022 +0800

    step to process confilct

```

### Steps to reproduce
>1、
please follow the video

**Comment by weikengchen** [comment]
do you think it is still the case, or we can close this PR?

**Comment by okovalov** [comment]
@weikengchen I have not seen this error for a long time already, I am assuming that was fixed as a part of the other fix. this is just an assumption since I have not seen any pr mentioning this particular issue.. probably it could be closed and if the issue arises again , we can address that separately

**Comment by harshadptl** [comment]
Yes, this failure was because of a bug in Block commit which has since been fixed. Closing this!
