### ISSUE TITLE
Node sometimes panics in ledger store module

### ISSUE THREAD

**Issue by harshadptl** [FindoraNetwork/platform#382]
### Problem Description
>description:
When a new devnet is started the node sometimes crashes due to panic

`thread 'actix-rt:worker:2' panicked at 'called `Result::unwrap()` on an `Err` value: SimpleError { msg: SimpleMsg { err: "...", file: "src/ledger/src/store/mod.rs", line: 1143, column: 62 }, cause: None }', src/ledger/src/store/mod.rs:866:74
stack backtrace:
   0:        0x107cab13c - std::backtrace_rs::backtrace::libunwind::trace::hce65e3f7a6c49d1b
                               at /rustc/fe5b13d681f25ee6474be29d748c65adcd91f69e/library/std/src/../../backtrace/src/backtrace/libunwind.rs:93:5
   1:        0x107cab13c - std::backtrace_rs::backtrace::trace_unsynchronized::h8e403a36971945a4
                               at /rustc/fe5b13d681f25ee6474be29d748c65adcd91f69e/library/std/src/../../backtrace/src/backtrace/mod.rs:66:5
   2:        0x107cab13c - std::sys_common::backtrace::_print_fmt::h01edb83516020417
                               at /rustc/fe5b13d681f25ee6474be29d748c65adcd91f69e/library/std/src/sys_common/backtrace.rs:66:5
   3:        0x107cab13c - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::hdb141e7893323405
                               at /rustc/fe5b13d681f25ee6474be29d748c65adcd91f69e/library/std/src/sys_common/backtrace.rs:45:22
   4:        0x107cc9358 - core::fmt::write::hed96bcfc6342aee5
                               at /rustc/fe5b13d681f25ee6474be29d748c65adcd91f69e/library/core/src/fmt/mod.rs:1194:17
   5:        0x107ca3d48 - std::io::Write::write_fmt::h67807909d9a5a6e1
                               at /rustc/fe5b13d681f25ee6474be29d748c65adcd91f69e/library/std/src/io/mod.rs:1655:15
   6:        0x107cacbc8 - std::sys_common::backtrace::_print::h7267448814343cd4
                               at /rustc/fe5b13d681f25ee6474be29d748c65adcd91f69e/library/std/src/sys_common/backtrace.rs:48:5
   7:        0x107cacbc8 - std::sys_common::backtrace::print::h83926e01abfb57bc
                               at /rustc/fe5b13d681f25ee6474be29d748c65adcd91f69e/library/std/src/sys_common/backtrace.rs:35:9
   8:        0x107cacbc8 - std::panicking::default_hook::{{closure}}::h23ab3d10a9c5bb0f
                               at /rustc/fe5b13d681f25ee6474be29d748c65adcd91f69e/library/std/src/panicking.rs:295:22
   9:        0x107cac8a4 - std::panicking::default_hook::hfa3eb92a01f5118c
                               at /rustc/fe5b13d681f25ee6474be29d748c65adcd91f69e/library/std/src/panicking.rs:314:9
  10:        0x104ecb63c - <alloc::boxed::Box<F,A> as core::ops::function::Fn<Args>>::call::h5613e450ae208ad0
                               at /rustc/fe5b13d681f25ee6474be29d748c65adcd91f69e/library/alloc/src/boxed.rs:1875:9
  11:        0x104fd8064 - abci::server::serve::{{closure}}::h0926f29c9e7a275d
                               at /Users/harshadpatil/.cargo/git/checkouts/tendermint-abci-1f83d9976c6442f1/3352482/src/server.rs:66:9
  12:        0x107cad13c - std::panicking::rust_panic_with_hook::h94fcfaabb5f8247c
                               at /rustc/fe5b13d681f25ee6474be29d748c65adcd91f69e/library/std/src/panicking.rs:702:17
  13:        0x107cacf94 - std::panicking::begin_panic_handler::{{closure}}::h5c2b0281f2361f0b
                               at /rustc/fe5b13d681f25ee6474be29d748c65adcd91f69e/library/std/src/panicking.rs:588:13
  14:        0x107cab618 - std::sys_common::backtrace::__rust_end_short_backtrace::h48848f94b4985ec4
                               at /rustc/fe5b13d681f25ee6474be29d748c65adcd91f69e/library/std/src/sys_common/backtrace.rs:138:18
  15:        0x107caccec - rust_begin_unwind
                               at /rustc/fe5b13d681f25ee6474be29d748c65adcd91f69e/library/std/src/panicking.rs:584:5
  16:        0x107cfc0b0 - core::panicking::panic_fmt::hfc743f4016412d36
                               at /rustc/fe5b13d681f25ee6474be29d748c65adcd91f69e/library/core/src/panicking.rs:143:14
  17:        0x107cfc154 - core::result::unwrap_failed::h964512213a00d9f4
                               at /rustc/fe5b13d681f25ee6474be29d748c65adcd91f69e/library/core/src/result.rs:1785:5
  18:        0x10601980c - core::result::Result<T,E>::unwrap::h93678f0a39a684eb
                               at /rustc/fe5b13d681f25ee6474be29d748c65adcd91f69e/library/core/src/result.rs:1078:23
  19:        0x1062f2ef4 - ledger::store::LedgerState::get_utxo::h6e22a207fa4f1f9a
                               at /Users/harshadpatil/Documents/GitHub/platform/src/ledger/src/store/mod.rs:866:37
  20:        0x104e076dc - abciapp::api::query_server::query_api::ledger_api::query_utxo::{{closure}}::hfe24a5ee292a12bd
                               at /Users/harshadpatil/Documents/GitHub/platform/src/components/abciapp/src/api/query_server/query_api/ledger_api.rs:47:28
  21:        0x104f62460 - <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll::h290e2d356d2b0cb1
                               at /rustc/fe5b13d681f25ee6474be29d748c65adcd91f69e/library/core/src/future/mod.rs:91:19
  22:        0x104ed9494 - <actix_web::handler::HandlerServiceResponse<T,R> as core::future::future::Future>::poll::h8fd390bd1b892248
                               at /Users/harshadpatil/.cargo/registry/src/github.com-1ecc6299db9ec823/actix-web-3.3.3/src/handler.rs:138:15
  23:        0x104f0a474 - <actix_web::handler::ExtractResponse<T,S> as core::future::future::Future>::poll::h378e85120b40409b
                               at /Users/harshadpatil/.cargo/registry/src/github.com-1ecc6299db9ec823/actix-web-3.3.3/src/handler.rs:247:20
  24:        0x104f0a834 - <actix_web::handler::ExtractResponse<T,S> as core::future::future::Future>::poll::h378e85120b40409b
                               at /Users/harshadpatil/.cargo/registry/src/github.com-1ecc6299db9ec823/actix-web-3.3.3/src/handler.rs:258:17
  25:        0x104fc4c14 - <futures_util::future::future::map::Map<Fut,F> as core::future::future::Future>::poll::hf6be405f981e6a88
                               at /Users/harshadpatil/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-util-0.3.21/src/future/future/map.rs:55:37
  26:        0x10503c3f4 - <futures_util::future::future::Map<Fut,F> as core::future::future::Future>::poll::he7b52c1c12d4def7
                               at /Users/harshadpatil/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-util-0.3.21/src/lib.rs:91:13
  27:        0x105a46aec - <core::pin::Pin<P> as core::future::future::Future>::poll::h98e177046bdf0f12
                               at /rustc/fe5b13d681f25ee6474be29d748c65adcd91f69e/library/core/src/future/future.rs:124:9
  28:        0x105a46aec - <core::pin::Pin<P> as core::future::future::Future>::poll::h98e177046bdf0f12
                               at /rustc/fe5b13d681f25ee6474be29d748c65adcd91f69e/library/core/src/future/future.rs:124:9
  29:        0x105a59050 - <futures_util::future::either::Either<A,B> as core::future::future::Future>::poll::h7c96245e1517898e
                               at /Users/harshadpatil/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-util-0.3.21/src/future/either.rs:90:33
  30:        0x105a46aec - <core::pin::Pin<P> as core::future::future::Future>::poll::h98e177046bdf0f12
                               at /rustc/fe5b13d681f25ee6474be29d748c65adcd91f69e/library/core/src/future/future.rs:124:9
  31:        0x104f19268 - <actix_web::middleware::logger::LoggerResponse<S,B> as core::future::future::Future>::poll::h9ac745876126913b
                               at /Users/harshadpatil/.cargo/registry/src/github.com-1ecc6299db9ec823/actix-web-3.3.3/src/middleware/logger.rs:285:46
  32:        0x104de4bec - <actix_cors::middleware::CorsMiddleware<S> as actix_service::Service>::call::{{closure}}::hbb8c82e46e422be3
                               at /Users/harshadpatil/.cargo/registry/src/github.com-1ecc6299db9ec823/actix-cors-0.5.4/src/middleware.rs:159:30
  33:        0x104f649c8 - <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll::hf1be0f820141b7d5
                               at /rustc/fe5b13d681f25ee6474be29d748c65adcd91f69e/library/core/src/future/mod.rs:91:19
  34:        0x104de3010 - <core::pin::Pin<P> as core::future::future::Future>::poll::h6178e93c2a8dfc02
                               at /rustc/fe5b13d681f25ee6474be29d748c65adcd91f69e/library/core/src/future/future.rs:124:9
  35:        0x104e7e1b0 - <futures_util::future::either::Either<A,B> as core::future::future::Future>::poll::h145ba58b3b0a0ec6
                               at /Users/harshadpatil/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-util-0.3.21/src/future/either.rs:90:33
  36:        0x104f8bddc - actix_http::h1::dispatcher::InnerDispatcher<T,S,B,X,U>::handle_request::h85460fb1a877f637
                               at /Users/harshadpatil/.cargo/registry/src/github.com-1ecc6299db9ec823/actix-http-2.2.2/src/h1/dispatcher.rs:500:15
  37:        0x104f88dcc - actix_http::h1::dispatcher::InnerDispatcher<T,S,B,X,U>::poll_request::hc7e0e3166dbee242
                               at /Users/harshadpatil/.cargo/registry/src/github.com-1ecc6299db9ec823/actix-http-2.2.2/src/h1/dispatcher.rs:560:45
  38:        0x104f8dcd4 - <actix_http::h1::dispatcher::Dispatcher<T,S,B,X,U> as core::future::future::Future>::poll::h1e88877ea7403fc6
                               at /Users/harshadpatil/.cargo/registry/src/github.com-1ecc6299db9ec823/actix-http-2.2.2/src/h1/dispatcher.rs:767:21
  39:        0x104f453c0 - actix_http::service::State<T,S,B,X,U>::poll::h578f6373c0175575
                               at /Users/harshadpatil/.cargo/registry/src/github.com-1ecc6299db9ec823/actix-http-2.2.2/src/service.rs:682:36
  40:        0x104f47fc8 - <actix_http::service::HttpServiceHandlerResponse<T,S,B,X,U> as core::future::future::Future>::poll::h1109d27ed980c2e6
                               at /Users/harshadpatil/.cargo/registry/src/github.com-1ecc6299db9ec823/actix-http-2.2.2/src/service.rs:661:9
  41:        0x104ee14e0 - <actix_service::and_then::AndThenServiceResponse<A,B> as core::future::future::Future>::poll::he1ac463607b72b71
                               at /Users/harshadpatil/.cargo/registry/src/github.com-1ecc6299db9ec823/actix-service-1.0.6/src/and_then.rs:101:34
  42:        0x104ecbf34 - <actix_server::service::StreamService<T> as actix_service::Service>::call::{{closure}}::hd78aa01a935a8ff6
                               at /Users/harshadpatil/.cargo/registry/src/github.com-1ecc6299db9ec823/actix-server-1.0.4/src/service.rs:85:34
  43:        0x104f63a34 - <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll::hb6708bca072d7c5f
                               at /rustc/fe5b13d681f25ee6474be29d748c65adcd91f69e/library/core/src/future/mod.rs:91:19
  44:        0x104eeef08 - tokio::runtime::task::core::Core<T,S>::poll::{{closure}}::h1b25a516c0c3a095
                               at /Users/harshadpatil/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-0.2.25/src/runtime/task/core.rs:173:17
  45:        0x104de072c - tokio::loom::std::unsafe_cell::UnsafeCell<T>::with_mut::he8feb6d6ad7a49c4
                               at /Users/harshadpatil/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-0.2.25/src/loom/std/unsafe_cell.rs:14:9
  46:        0x104eeed54 - tokio::runtime::task::core::Core<T,S>::poll::h6f2dcd7cf2c3f181
                               at /Users/harshadpatil/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-0.2.25/src/runtime/task/core.rs:158:13
  47:        0x104e6f2a4 - tokio::runtime::task::harness::Harness<T,S>::poll::{{closure}}::hdb97fd2be4f69b55
                               at /Users/harshadpatil/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-0.2.25/src/runtime/task/harness.rs:107:27
  48:        0x104db4484 - core::ops::function::FnOnce::call_once::heabc3b6eecf6138a
                               at /rustc/fe5b13d681f25ee6474be29d748c65adcd91f69e/library/core/src/ops/function.rs:227:5
  49:        0x104e1c7dc - <core::panic::unwind_safe::AssertUnwindSafe<F> as core::ops::function::FnOnce<()>>::call_once::h1845f11e102bde3c
                               at /rustc/fe5b13d681f25ee6474be29d748c65adcd91f69e/library/core/src/panic/unwind_safe.rs:271:9
  50:        0x105027a80 - std::panicking::try::do_call::h38719332c4eff8b6
                               at /rustc/fe5b13d681f25ee6474be29d748c65adcd91f69e/library/std/src/panicking.rs:492:40
  51:        0x10503c638 - ___rust_try
  52:        0x1050276c8 - std::panicking::try::h827d95191d2abe87
                               at /rustc/fe5b13d681f25ee6474be29d748c65adcd91f69e/library/std/src/panicking.rs:456:19
  53:        0x104ee82d8 - std::panic::catch_unwind::h7f6b8e489ffeb7d7
                               at /rustc/fe5b13d681f25ee6474be29d748c65adcd91f69e/library/std/src/panic.rs:137:14
  54:        0x104e6e694 - tokio::runtime::task::harness::Harness<T,S>::poll::ha7d23d8b9605e20e
                               at /Users/harshadpatil/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-0.2.25/src/runtime/task/harness.rs:89:19
  55:        0x104eecab4 - tokio::runtime::task::raw::poll::hbee1377f43209ccb
                               at /Users/harshadpatil/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-0.2.25/src/runtime/task/raw.rs:104:5
  56:        0x107930794 - tokio::runtime::task::raw::RawTask::poll::h85fba28ebc3e96a7
                               at /Users/harshadpatil/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-0.2.25/src/runtime/task/raw.rs:66:18
  57:        0x107930a48 - tokio::runtime::task::Notified<S>::run::h622b81b94dadb298
                               at /Users/harshadpatil/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-0.2.25/src/runtime/task/mod.rs:169:9
  58:        0x1079067f4 - tokio::task::local::LocalSet::tick::{{closure}}::h90b8440fd7481401
                               at /Users/harshadpatil/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-0.2.25/src/task/local.rs:408:54
  59:        0x10794022c - tokio::coop::with_budget::{{closure}}::haf0da1efe81392a9
                               at /Users/harshadpatil/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-0.2.25/src/coop.rs:127:9
  60:        0x10791d52c - std::thread::local::LocalKey<T>::try_with::h4a5d63db7a2984ee
                               at /rustc/fe5b13d681f25ee6474be29d748c65adcd91f69e/library/std/src/thread/local.rs:442:16
  61:        0x10791c7d0 - std::thread::local::LocalKey<T>::with::h069f5a6349434320
                               at /rustc/fe5b13d681f25ee6474be29d748c65adcd91f69e/library/std/src/thread/local.rs:418:9
  62:        0x1079067a0 - tokio::coop::with_budget::h3b1c3997d19e2551
                               at /Users/harshadpatil/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-0.2.25/src/coop.rs:120:5
  63:        0x1079067a0 - tokio::coop::budget::hd938d6970e8c4b42
                               at /Users/harshadpatil/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-0.2.25/src/coop.rs:96:5
  64:        0x1079067a0 - tokio::task::local::LocalSet::tick::hf0374770fb1d3bb1
                               at /Users/harshadpatil/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-0.2.25/src/task/local.rs:408:31
  65:        0x105c00488 - <tokio::task::local::RunUntil<T> as core::future::future::Future>::poll::{{closure}}::h8b649e21884468ca
                               at /Users/harshadpatil/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-0.2.25/src/task/local.rs:532:16
  66:        0x105c02d7c - tokio::macros::scoped_tls::ScopedKey<T>::set::haf34fd7823dd6e3d
                               at /Users/harshadpatil/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-0.2.25/src/macros/scoped_tls.rs:63:9
  67:        0x105bff960 - tokio::task::local::LocalSet::with::h252dddb6c2f0265f
                               at /Users/harshadpatil/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-0.2.25/src/task/local.rs:442:9
  68:        0x105c00218 - <tokio::task::local::RunUntil<T> as core::future::future::Future>::poll::h32dd32ffe9bae9a1
                               at /Users/harshadpatil/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-0.2.25/src/task/local.rs:518:9
  69:        0x105bffc48 - tokio::task::local::LocalSet::run_until::{{closure}}::h5dd327fee68bb64b
                               at /Users/harshadpatil/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-0.2.25/src/task/local.rs:392:18
  70:        0x105bfbe30 - <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll::hd6baab2bea2fb380
                               at /rustc/fe5b13d681f25ee6474be29d748c65adcd91f69e/library/core/src/future/mod.rs:91:19
  71:        0x105becbd4 - tokio::runtime::basic_scheduler::BasicScheduler<P>::block_on::{{closure}}::{{closure}}::h13365eb5fb82668d
                               at /Users/harshadpatil/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-0.2.25/src/runtime/basic_scheduler.rs:131:58
  72:        0x105c0bfe4 - tokio::coop::with_budget::{{closure}}::hff59316c0722b6ab
                               at /Users/harshadpatil/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-0.2.25/src/coop.rs:127:9
  73:        0x105bf1ab4 - std::thread::local::LocalKey<T>::try_with::h70f2836558658061
                               at /rustc/fe5b13d681f25ee6474be29d748c65adcd91f69e/library/std/src/thread/local.rs:442:16
  74:        0x105bf00c4 - std::thread::local::LocalKey<T>::with::h1d6ef758085ba1a6
                               at /rustc/fe5b13d681f25ee6474be29d748c65adcd91f69e/library/std/src/thread/local.rs:418:9
  75:        0x105bec13c - tokio::coop::with_budget::h8b02679215fedbb1
                               at /Users/harshadpatil/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-0.2.25/src/coop.rs:120:5
  76:        0x105bec13c - tokio::coop::budget::hcecbb36afa72d4df
                               at /Users/harshadpatil/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-0.2.25/src/coop.rs:96:5
  77:        0x105bec13c - tokio::runtime::basic_scheduler::BasicScheduler<P>::block_on::{{closure}}::h8fad889fbed00ef5
                               at /Users/harshadpatil/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-0.2.25/src/runtime/basic_scheduler.rs:131:35
  78:        0x105bed338 - tokio::runtime::basic_scheduler::enter::{{closure}}::h94676c18841a2c15
                               at /Users/harshadpatil/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-0.2.25/src/runtime/basic_scheduler.rs:213:29
  79:        0x105c02b88 - tokio::macros::scoped_tls::ScopedKey<T>::set::h902682a5297f1c39
                               at /Users/harshadpatil/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-0.2.25/src/macros/scoped_tls.rs:63:9
  80:        0x105bed238 - tokio::runtime::basic_scheduler::enter::he74c34ac6f058bbb
                               at /Users/harshadpatil/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-0.2.25/src/runtime/basic_scheduler.rs:213:5
  81:        0x105bebf3c - tokio::runtime::basic_scheduler::BasicScheduler<P>::block_on::h888d2d12ea01363a
                               at /Users/harshadpatil/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-0.2.25/src/runtime/basic_scheduler.rs:123:9
  82:        0x105c07b54 - tokio::runtime::Runtime::block_on::{{closure}}::hed18b2712f51235d
                               at /Users/harshadpatil/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-0.2.25/src/runtime/mod.rs:444:34
  83:        0x105c1d74c - tokio::runtime::context::enter::hfe777f6b097e8964
                               at /Users/harshadpatil/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-0.2.25/src/runtime/context.rs:72:5
  84:        0x105c07890 - tokio::runtime::handle::Handle::enter::h472b155b8bf536bc
                               at /Users/harshadpatil/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-0.2.25/src/runtime/handle.rs:76:9
  85:        0x105c079ec - tokio::runtime::Runtime::block_on::hab8e52d65ecba59e
                               at /Users/harshadpatil/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-0.2.25/src/runtime/mod.rs:441:9
  86:        0x105bffa18 - tokio::task::local::LocalSet::block_on::hc29ebec790781c85
                               at /Users/harshadpatil/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-0.2.25/src/task/local.rs:353:9
  87:        0x105c08854 - actix_rt::runtime::Runtime::block_on::hf69f93a37db23ba9
                               at /Users/harshadpatil/.cargo/registry/src/github.com-1ecc6299db9ec823/actix-rt-1.1.1/src/runtime.rs:89:9
  88:        0x105c10c60 - actix_rt::arbiter::Arbiter::new::{{closure}}::h3f2e98a682cc14d7
                               at /Users/harshadpatil/.cargo/registry/src/github.com-1ecc6299db9ec823/actix-rt-1.1.1/src/arbiter.rs:137:31
  89:        0x105bfe8d0 - std::sys_common::backtrace::__rust_begin_short_backtrace::h5a41244e2d7efc7a
                               at /rustc/fe5b13d681f25ee6474be29d748c65adcd91f69e/library/std/src/sys_common/backtrace.rs:122:18
  90:        0x105c06988 - std::thread::Builder::spawn_unchecked_::{{closure}}::{{closure}}::h4e71b4ff9c8dc610
                               at /rustc/fe5b13d681f25ee6474be29d748c65adcd91f69e/library/std/src/thread/mod.rs:498:17
  91:        0x105c088c8 - <core::panic::unwind_safe::AssertUnwindSafe<F> as core::ops::function::FnOnce<()>>::call_once::h449f204e71e27bad
                               at /rustc/fe5b13d681f25ee6474be29d748c65adcd91f69e/library/core/src/panic/unwind_safe.rs:271:9
  92:        0x105c0f9bc - std::panicking::try::do_call::hd6946921e3e4cc92
                               at /rustc/fe5b13d681f25ee6474be29d748c65adcd91f69e/library/std/src/panicking.rs:492:40
  93:        0x105c12994 - ___rust_try
  94:        0x105c0f414 - std::panicking::try::hdc958e5e842f3725
                               at /rustc/fe5b13d681f25ee6474be29d748c65adcd91f69e/library/std/src/panicking.rs:456:19
  95:        0x105c05430 - std::panic::catch_unwind::h600074665d77e5d8
                               at /rustc/fe5b13d681f25ee6474be29d748c65adcd91f69e/library/std/src/panic.rs:137:14
  96:        0x105c06800 - std::thread::Builder::spawn_unchecked_::{{closure}}::h7620f80e2f57afde
                               at /rustc/fe5b13d681f25ee6474be29d748c65adcd91f69e/library/std/src/thread/mod.rs:497:30
  97:        0x105bf7ecc - core::ops::function::FnOnce::call_once{{vtable.shim}}::h168d8455333f39ad
                               at /rustc/fe5b13d681f25ee6474be29d748c65adcd91f69e/library/core/src/ops/function.rs:227:5
  98:        0x107cb1ae8 - <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once::he61adb88e08482e6
                               at /rustc/fe5b13d681f25ee6474be29d748c65adcd91f69e/library/alloc/src/boxed.rs:1861:9
  99:        0x107cb1ae8 - <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once::h6c3a6509e86eb898
                               at /rustc/fe5b13d681f25ee6474be29d748c65adcd91f69e/library/alloc/src/boxed.rs:1861:9
 100:        0x107cb1ae8 - std::sys::unix::thread::Thread::new::thread_start::h0302a0ad0f27d8f0
                               at /rustc/fe5b13d681f25ee6474be29d748c65adcd91f69e/library/std/src/sys/unix/thread.rs:108:17
 101:        0x195adb878 - _pthread_jit_write_protect_np
`
>Screenshots:

### Environmental information
>operating system:
MacOS

>service:
abcid

>Code version:
develop

### Steps to reproduce
>1、
Start a new devnet a couple of times with `make devnet`
>2、
Tail logs, the node sometimes crashes
>3、

**Comment by tiannian** [comment]
Did you make any request?  Check balances?

**Comment by harshadptl** [comment]
Yes, this panic happens during check balance query server call.

**Comment by harshadptl** [comment]
I did some research on this issue. It happens when 
1. a new network is started
2.  and the state_commitment_data is set to default None
3. a block is in the process of being committed 
4. and a query_utxo API is called which tries to unwrap the state_commitment_data.


Closing this issue because it is an edge case which is unlikely to be produced on mainnet.

**Comment by tiannian** [comment]
Fix by PR #388
