### ISSUE TITLE
Contract Deposit not working on address-folding branch

### ISSUE THREAD

**Issue by harshadptl** [FindoraNetwork/platform#520]
### Problem Description
>description:
This commit changes Address32 datatype to Address 34 https://github.com/FindoraNetwork/platform/commit/a03b9e8ea420118caba56f16cf6f0bc5df3272d7
to accommodate increased size of Secp Public key

The Prism contracts take from parameter as bytes32 in solidity. So the Prism Withdraw deposit is failing.

>Screenshots:

### Environmental information
>operating system:

>service:

>Code version:

### Steps to reproduce
>1、
checkout address-folding branch on platform
>2、
make build_release

>3、
make prismtest

**Comment by harshadptl** [comment]
Will have to consider mainnet compatibility while upgrading because mainnet is using old Prism

**Comment by findora-sun** [comment]
OK, let's talk with @tiannian more about this and also discussing the impact on Prism 2.

**Comment by tiannian** [comment]
I need more detail.

**Comment by harshadptl** [comment]
Issue resolved in address-folding branch
