### ISSUE TITLE
Did not destroy utxo equal to 0

### ISSUE THREAD

**Issue by DomFeng** [FindoraNetwork/platform#66]
### Problem Description
>description:
There are many utxo equal to 0 in the account

>Screenshots:
![image](https://user-images.githubusercontent.com/61138066/137691390-412d98ca-140c-4f03-99d9-dc6295c01ae8.png)

### Environmental information
>operating system:
ubuntu

>service:
findora testnet

>Code version:
Build: v0.2.0-release 2021-10-18

### Steps to reproduce
>1、https://prod-testnet.prod.findora.org:8668/utxo_sid/221

**Comment by kevinssgh** [comment]
What is the scenario where zero value UTXO's are not cleared? 

Is it after a transfer from UTXO -> Account or from UTXO->UTXO?

I'll need more details regarding the actual steps to reproduce.

**Comment by kingpinXD** [comment]
Fixed
