### ISSUE TITLE
16-bit precision transfer error

### ISSUE THREAD

**Issue by DomFeng** [FindoraNetwork/platform#77]
### Problem Description
>description:
创建自定义资产为16位精度，转账失败

>Screenshots:
前端排查是由rust 方法抛出错误 undefind
![image](https://user-images.githubusercontent.com/61138066/138243997-d8fad6d6-b481-4fbd-a1f8-ff97d5690434.png)

### Environmental information
>operating system:
ubuntu

>service:
findora

>Code version:
QA02:Build: v0.2.2-RC3 2021-10-19

### Steps to reproduce
>1、wallet1创建资产asset1，精度为16

>2、wallet1向wallet2转账asset1资产1.0000000000000001

>3、转账失败

**Comment by 1160007652** [comment]
假如 ： u64 的最大可表示的数字范围是 10，我第一次发行 6，第二次发行5，第三次发行3 ， 哪总数（金额）不就是 6 + 5 + 3 = 14

我转账时限制，每次转账的金额（必须小于10）

那我转账的时候，转8个fra， 把  balance：6 和 balance 5  这两笔 utxo 消费掉。返回一个（找零 balance：3，【不考虑手续费的情况】）

此时，2个用来消费的input - utxo 总和不就 6+5 >10 了吗
 
我在设计前端编码时，所有的数字都是使用的字符串编码
 
字符串大数拆分计算
